# Generated by Django 4.0.5 on 2022-06-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=100)),
                ('campeonatos', models.IntegerField()),
                ('ultcampeonato', models.IntegerField()),
                ('colores', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('equipoact', models.CharField(max_length=100)),
                ('equipos', models.CharField(max_length=100)),
                ('campeonatos', models.CharField(max_length=100)),
                ('allstar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=100)),
                ('campeon', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('fmvp', models.CharField(max_length=100)),
                ('mvp', models.CharField(max_length=100)),
                ('record', models.CharField(max_length=100)),
                ('defensa', models.CharField(max_length=100)),
            ],
        ),
    ]
